### ISSUE TITLE
Nesting directory

### ISSUE THREAD

**Issue by gebv** [fader2/platform#4]
Маска ресурса базируется на `bucket_name` и `filename` где `filename` может быть файлом вложенным в дирикторию.

Например `project_name/foo/bar/file.extenction`

Требуется реализовать импортер\экспортер для вложенных файлов.
Текущая реализация не умеет импортировать и экспортировать файлы вложенные в дирикторию в рамках бакета.

**Comment by gebv** [comment]
## Экспортер

Существующие файлы в бакете вложенность которых больше 1 размещать в поддирикториях.

## Импортер

**Нюанс 1.**
Пустые дириктории не синхронизировать. Что это значит? В случае когда включен режим `watch` и добавляется новый файл в дириктори, в какой то момент времени существует пустая дириктория в котором чуть позже будет создаваться файл. Во первых пустою дирикторию не надо добавлять в проект пока в нем не появится файл. Во вторых в ватчере добавить дирикторию для наблюдения. В проекте же создается в рамках бакета файл с именем равным значению пути файла + сам файл. 

Например бакет `static` файл `images/logo1.png`. В этом случае в файловой системе (в результате работы фатчера) создается дириктория `images` в бакете `static` и в дириктории `images` добавляется файл `logo1.png`. В проекте файл имеет имя `images/logo1.png`.

**Comment by zhuharev** [comment]
При импорте, если есть, например `file.html.json`, но нету `file.html`, то импорта не призойдет.

**Comment by zhuharev** [comment]
Добавил ипорт вложенных файлов zhuharev@1b6e184c3899c0e637e9d1e1d1d32d4ddf8e5ae8

**Comment by gebv** [comment]
Тесткейс
Создается дириктория `newfolder1`. Создается в нем файл `newfile.txt`. Создается новая дириктория `newfolder2`. Перемещается в него из дириктории `newfolrder1` файл `newfile.txt`. В итоге содержимое бакета следующее

```
newfolder1
newfolder1/newfile.txt
newfolder2/newfile.txt
```

Ожидаемое содержимое
```
newfolder2/newfile.txt
```

Лог

```
2017/06/08 09:25:22 [Create new file] Create file /test1/newfolder1/newfile.txt
2017/06/08 09:25:22 we need update file, with newfolder1/newfile.txt filename, test1 bucketname
2017/06/08 09:25:22 [IMPORT] test1/newfolder1/newfile.txt
2017/06/08 09:25:35 [Create new file] Create file /test1/newfolder2/newfile.txt
2017/06/08 09:25:35 we need update file, with newfolder2/newfile.txt filename, test1 bucketname
2017/06/08 09:25:35 [IMPORT] test1/newfolder2/newfile.txt
we need update file, with newfolder1 filename, test1 bucketname
IMPORT FaderWorkspace/test1/newfolder1 [FaderWorkspace/test1/newfolder1] newfolder1
2017/06/08 09:25:35 [WATCHER ERR] read FaderWorkspace/test1/newfolder1: is a directory
```

**Comment by gebv** [comment]
(https://s3.amazonaws.com/idheap/ss/1._bash_2017-06-09_11-59-42.png)[https://s3.amazonaws.com/idheap/ss/1._bash_2017-06-09_11-59-42.png]

Выполнен только экспорт и в файловой системе не ожидаемое состояние файлов

**Comment by gebv** [comment]
Не актуально
